package impossible;

import java.awt.Color;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gautham
 */
public class game extends javax.swing.JFrame {
    static String s;

    String[][] qpa;
    String[][] qca;
    int score;
    int q=0;
    int count;
    int position=1;
    int maxSize=5;
    /**
     * Creates new form game
     */
	public game() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		pack();
		initComponents();
		score = 0;
		count = 0;
		qpa = new String[5][5];

		qpa[0][0] = "How to run Java program on the command prompt?";
		qpa[0][1] = "javac JavaProgram";
		qpa[0][2] = "java JavaProgram";
		qpa[0][3] = "javac JavaProgram.java";
		qpa[0][4] = "No one";

		qpa[1][0] = "What is the use of the println method?";
		qpa[1][1] = "It is used to print text on the screen.";
		qpa[1][2] = "It is used to print text on the screen with the line break.";
		qpa[1][3] = "It is used to read text from keyboard.";
		qpa[1][4] = "It is used to read text from a file.";

		qpa[2][0] = "How to read a character from the keyboard?";
		qpa[2][1] = "char c=System.read()";
		qpa[2][2] = "char c=System.in.read()";
		qpa[2][3] = "char c=(char)System.read()";
		qpa[2][4] = "char c=(char)System.in.read()";

		qpa[3][0] = "Which one is a single-line comment?";
		qpa[3][1] = "/...";
		qpa[3][2] = "//...";
		qpa[3][3] = "/*...";
		qpa[3][4] = "/*...*/";

		qpa[4][0] = "How do you declare an integer variable x?";
		qpa[4][1] = "int x";
		qpa[4][2] = "x as Integer";
		qpa[4][3] = "Int[] x";
		qpa[4][4] = "No one is correct.";

		// qca stores pairs of question and its correct answer
		qca = new String[10][2];

		qca[0][0] = "How to run Java program on the command prompt?";
		qca[0][1] = "java JavaProgram";

		qca[1][0] = "What is the use of the println method?";
		qca[1][1] = "It is used to print text on the screen with the line break.";

		qca[2][0] = "How to read a character from the keyboard?";
		qca[2][1] = "char c=(char)System.in.read()";

		qca[3][0] = "Which one is a single-line comment?";
		qca[3][1] = "//...";

		qca[4][0] = "How do you declare an integer variable x?";
		qca[4][1] = "int x";
		
		maxSize=qpa.length;

		start(0);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jColorChooser1 = new javax.swing.JColorChooser();
        bg = new javax.swing.ButtonGroup();
        b1 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        //jLabel2 = new javax.swing.JLabel();
        bbnxt = new javax.swing.JButton();
        skip = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.add(b1);
        b1.setText("option1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        bg.add(b2);
        b2.setText("jRadioButton2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        bg.add(b3);
        b3.setText("jRadioButton3");

        bg.add(b4);
        b4.setText("jRadioButton4");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        /*
        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setText("Score:000");
        */

        if(position<maxSize){
        	bbnxt.setText("Next");
            bbnxt.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bbnxtActionPerformed(evt);
                }
            });
        }
        

        skip.setText("Check Answer"); //Check Result
        skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        Color customColor = new Color(238, 112, 1);
        getContentPane().setBackground(customColor);        
        
       
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b1)
                        .addComponent(b3)
                        .addComponent(b2)
                        .addComponent(b4))
                    )
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                	.addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(layout.createSequentialGroup()
                        		.addGap(642, 642, 642)))
                    .addGap(21, 21, 21))
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        		.addComponent(bbnxt, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        		.addComponent(skip, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        )
                /*.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())*/
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()                    
                	.addGap(25, 25, 25)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(b1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(b2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(b3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(b4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                    		.addComponent(skip, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    		.addComponent(bbnxt, javax.swing.GroupLayout.DEFAULT_SIZE,20, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                    //.addComponent(jButton1)
                    //.addContainerGap()
                    )
            );

        

        pack();
    }// </editor-fold>                        

    
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

	String getSelectedButtonText(ButtonGroup buttonGroup) {
		for (Enumeration buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
			AbstractButton button = (AbstractButton) buttons.nextElement();

			if (button.isSelected()) {
				return button.getText();
			}
		}

		return null;
	}

	private void bbnxtActionPerformed(java.awt.event.ActionEvent evt) {
		if (getSelectedButtonText(bg) == qca[q][1]) {
			score = score + 100;

		} else {
			count++;
		}
		q++;
		if (q < maxSize) {
			start(q);
			
		} else {
			dispose();
			end e = new end();
			e.ending(score, s);
		}

		// jLabel2.setText("Score :" + score);
		System.out.println(score + " and " + count);
		// TODO add your handling code here:
	}                      

    private void skipActionPerformed(java.awt.event.ActionEvent evt) {
	    	if (getSelectedButtonText(bg) == qca[q][1]) {
				score = score + 100;
				JOptionPane.showMessageDialog(null, "Correct");
			}else{
				JOptionPane.showMessageDialog(null, "Wrong");
			}
            //q++;
            start(q);
        // TODO add your handling code here:
    }                                    

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		System.exit(0);
		// TODO add your handling code here:
	}
                                 
    public void start(int i){
        
            jLabel1.setText(qpa[i][0]);
            b1.setText(qpa[i][1]);
            b2.setText(qpa[i][2]);
            b3.setText(qpa[i][3]);
            b4.setText(qpa[i][4]);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void Newgame(String user) {
        /* Set the Nimbu
        s look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		s = user;
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new game().setVisible(true);
			}
		});
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    //private java.awt.Button bbnxt;
    private javax.swing.JButton bbnxt;
    private javax.swing.ButtonGroup bg;
    //private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    //private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton skip;
    // End of variables declaration                   
}